---
title: "QuestionsPMHD"
author: "Henry Hockliffe"
date: "2024-05-03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(lme4)
library(reshape2)
library(lattice)
library(ggplot2)
```

### Question b


```{r}
gaussianData<- read.csv("C:/Users/Moi/Downloads/gaussian_data_G17.csv")

gaussianLongformat<- melt(gaussianData, id.vars = c("Flower_index", "Compound", "Rater", "Type", "Garden", "Subplot"),
                      variable.name = "Day", value.name = "Width")
gaussianLongformat$Day <- as.numeric(gsub("T_", "", gaussianLongformat$Day))

gaussianLongformat$Width <- ifelse(is.na(gaussianLongformat$Width), ave(gaussianLongformat$Width, gaussianLongformat$Day, FUN = function(x) mean(x, na.rm = TRUE)), gaussianLongformat$Width)

mixedModel<- lmer(log(Width) ~ Day + Compound + Type + Garden + Rater + (1 | Subplot), data = gaussianLongformat, control = lmerControl(optimizer = "bobyqa", optCtrl = list(maxfun = 100000)))

summary(mixedModel)

qqmath(mixedModel)
```

### Question d

```{r}
pcaData<- gaussianLongformat[, c("Width", "Day")]

pcaData<- scale(pcaData)

pcaResult<- prcomp(pcaData, center = TRUE, scale. = TRUE)

summary(pcaResult)

screePlot<- data.frame(Variance = pcaResult$sdev^2 / sum(pcaResult$sdev^2),
                         PC = factor(1:length(pcaResult$sdev), levels = 1:length(pcaResult$sdev)))
ggplot(screePlot, aes(x = PC, y = Variance)) +
  geom_bar(stat = "identity", fill = "steelblue") +
  theme_minimal() +
  labs(title = "Scree Plot", x = "Principal Component", y = "Proportion of Variance Explained")

scores <- pcaResult$x

loadings <- pcaResult$rotation

plot(scores[, 1], scores[, 2], xlab = "PC1", ylab = "PC2", main = "PCA Score Plot")
text(scores[, 1], scores[, 2], labels = rownames(scores), pos = 4, cex = 0.6)
points(loadings[, 1] * max(abs(scores[, 1])), loadings[, 2] * max(abs(scores[, 2])), col = "red")
text(loadings[, 1] * max(abs(scores[, 1])), loadings[, 2] * max(abs(scores[, 2])), labels = colnames(pcaData), col = "red")
```
