---
title: "PHMD Analysis"
author: "Görkem Uyanık"
date: "2023-05-07"
output:
  pdf_document:
    latex_engine: xelatex
  html_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, message=FALSE}
library(tidyr)
library(tidyverse)
library(lme4)
library(lmerTest)
library(nlme)
library(car)
library(performance)
library(ggplot2)
library(multcomp)
library(DescTools)
library(optimx)
library(nloptr)
library(dfoptim)
library(broom)
library(broom.mixed)
library(reshape2)
library(recipes)
library(emmeans)
library(dplyr)
```


```{r}
count_data <- read.csv("count_data_G17.csv") %>% na.omit()
dim(count_data)
head(count_data)

count_data <- count_data %>% rename("tot_vase_days" = "tot.vase.days")
max_days <- max(count_data$tot_vase_days)
max_days
```


```{r}
count_data$species_factor <- as.factor(count_data$species)
count_data$compound_factor <- as.factor(count_data$compound)
count_data$flowerID_factor <- as.factor(count_data$flowerID)
count_data$rater_factor <- as.factor(count_data$rater)
count_data$subplotID_factor <- as.factor(count_data$subplotID)
count_data$garden_factor <- as.factor(count_data$garden)
```


```{r}
poisson_glmer <- glmer(
  tot_vase_days ~ 
  compound_factor +
  garden_factor +
  species_factor +
  (1 | subplotID_factor) +
  (1 | rater_factor) +
  (1 | flowerID_factor),
  data = count_data,
  family = poisson,
  control=glmerControl(optimizer="optimx",
                       optCtrl=list(method="nlminb")), 
  nAGQ = 0
)

car::Anova(poisson_glmer, type=3)

print(summary(poisson_glmer), correlation = FALSE)
```

```{r}
confint(poisson_glmer, method = "Wald")
```


```{r}
emm = emmeans(poisson_glmer, ~ compound_factor)
contrast(emm, method = "dunnett", adjust = "bonferroni")
```


```{r}
qqnorm(resid(poisson_glmer), pch = 1, frame = FALSE)
qqline(resid(poisson_glmer), col = "steelblue", lwd = 2)
```


```{r}
count_data <- read.csv("count_data_G10.csv") %>% na.omit()
dim(count_data)
head(count_data)

count_data <- count_data %>% rename("tot_vase_days" = "tot.vase.days")
max_days <- max(count_data$tot_vase_days)
max_days
```


```{r}
for (flower in 1:nrow(count_data)) {
  for (i in 1:max_days) {
    if (i <= count_data[flower, "tot_vase_days"]) {
      count_data[flower, as.character(i)] <- as.integer(1)
    } else {
      count_data[flower, as.character(i)] <- as.integer(0)
    }
  }
}


count_data_long <- 
  pivot_longer(count_data, cols = 8:32, 
               names_to = "day_temp", 
               values_to = "fresh") %>% 
  mutate(day = as.integer(day_temp)) %>%
  dplyr::select(-day_temp)

#count_data_long <- count_data_long[, -8:-32]

count_data_long$day <- count_data_long$day

head(count_data_long)

write.csv(count_data_long, "count_data_long_binary_G10.csv")
```


```{r}
sum_count_data <- count_data_long %>% 
  group_by(day, compound) %>% 
  summarise(fresh_sum = sum(fresh))

sum_count_data

sum_count_data %>%
  ggplot(aes(day, fresh_sum, color = as.factor(compound))) + geom_line()
```


```{r}
count_data_long$fresh_factor <- as.factor(count_data_long$fresh)
count_data_long$species_factor <- as.factor(count_data_long$species)
count_data_long$compound_factor <- as.factor(count_data_long$compound)
count_data_long$flowerID_factor <- as.factor(count_data_long$flowerID)
count_data_long$rater_factor <- as.factor(count_data_long$rater)
count_data_long$subplotID_factor <- as.factor(count_data_long$subplotID)
count_data_long$garden_factor <- as.factor(count_data_long$garden)
```




```{r}
fixed_slope_glmer <- glmer(
  fresh ~ day +
  compound_factor:day +
  garden_factor +
  species_factor +
  (1 | subplotID_factor) +
  (1 | rater_factor) +
  (1 | flowerID_factor),
  data = count_data_long,
  family = binomial,
  control=glmerControl(optimizer="optimx",
                       optCtrl=list(method="nlminb")), 
  nAGQ = 0
)

car::Anova(fixed_slope_glmer, type=3)

print(summary(fixed_slope_glmer), correlation = FALSE)
```

```{r}
confint(fixed_slope_glmer, method = "Wald")
```


```{r}
emm = emmeans(fixed_slope_glmer, ~ compound_factor | day)
contrast(emm, method = "dunnett", adjust = "bonferroni")
```


```{r}
qqnorm(count_data_long$fresh, pch = 1, frame = FALSE)
qqline(count_data_long$fresh, col = "steelblue", lwd = 2)
qqnorm(resid(fixed_slope_glmer), pch = 1, frame = FALSE)
qqline(resid(fixed_slope_glmer), col = "steelblue", lwd = 2)
```


```{r}
random_slope_glmer <- glmer(
  fresh ~ day +
  compound_factor:day +
  species_factor +
  (1 | subplotID_factor) +
  (1 | rater_factor) +
  (day | flowerID_factor),
  data = count_data_long,
  family = binomial,
  control=glmerControl(optimizer="optimx",
                       optCtrl=list(method="nlminb")), 
  nAGQ = 0
)

print(summary(random_slope_glmer), correlation = FALSE)
```


```{r}
emm = emmeans(random_slope_glmer, ~ compound_factor:day)
contrast(emm, method = "dunnett", adjust = "bonferroni")
```











This part is just for finding the best working model.










```{r}
hebele
```



```{r}
diff_optims <- allFit(random_slope_glmer)
```

```{r}
glance(diff_optims) |> dplyr::select(optimizer, AIC, NLL_rel) |> arrange(NLL_rel)
```

```{r}
tidy(diff_optims, conf.int = TRUE) |> 
     arrange(effect, term, estimate) |> 
     dplyr::select(-c(std.error, statistic))
```

```{r}
aa <- diff_optims
(lliks <- sort(sapply(aa.OK,logLik)))
```


```{r}
aa.fixef <- t(sapply(aa.OK,fixef))
aa.fixef.m <- melt(aa.fixef)
models <- levels(aa.fixef.m$Var1)
ylabs <- substr(models,1,3)
aa.fixef.m <- transform(aa.fixef.m,Var1=factor(Var1,levels=names(lliks)))
(gplot1 <- ggplot(aa.fixef.m,aes(x=value,y=Var1,colour=Var1))+geom_point()+
     facet_wrap(~Var2,scale="free")+
         scale_colour_brewer(palette="Dark2")+
             scale_y_discrete(breaks=models,
                              labels=ylabs)+
                                  labs(x="",y=""))
```


```{r}
aa.stddev <- t(sapply(aa.OK,function(x) sqrt(unlist(VarCorr(x)))))
print(aa.stddev,digits=3)
```


```{r}
numcols <- grep("^c\\.",names(count_data_long))
dfs <- count_data_long
dfs[,numcols] <- scale(dfs[,numcols])
m1_sc <- update(random_slope_glmer,data=dfs)
```
```{r}
print(summary(m1_sc), correlation = FALSE)
```

```{r}
tt <- getME(m1_sc,"theta")
ll <- getME(m1_sc,"lower")
min(tt[ll==0])
```

```{r}
derivs1 <- m1_sc@optinfo$derivs
sc_grad1 <- with(derivs1,solve(Hessian,gradient))
max(abs(sc_grad1))
```

```{r}
max(pmin(abs(sc_grad1),abs(derivs1$gradient)))
```

```{r}
ss <- getME(m1_sc,c("theta","fixef"))
m2 <- update(m1_sc,start=ss,control=glmerControl(optCtrl=list(maxfun=2e4)))
```
