---
title: "PHMD Analysis"
author: "Görkem Uyanık"
date: "2023-05-07"
output:
  pdf_document:
    latex_engine: xelatex
  html_document: default
  word_document: default
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, message=FALSE}
library(tidyr)
library(lme4)
library(lmerTest)
library(nlme)
library(performance)
library(ggplot2)
library(multcomp)
library(DescTools)
library(optimx)
library(emmeans)
library(dplyr)
```


```{r}
gaussian_data <- read.csv("gaussian_data_G17.csv") %>% na.omit()
dim(gaussian_data)
head(gaussian_data)
```


```{r}
gaussian_data_long <- pivot_longer(gaussian_data, cols = starts_with("T_"), 
                            names_to = "Day_temp", values_to = "Width") %>%
  mutate(Day = as.integer(substr(Day_temp, 3, nchar(Day_temp)))) %>%
  dplyr::select(-Day_temp)

head(gaussian_data_long)
```


```{r}
# fixed_slope_lme <- lme(Width ~ Day +
#     as.factor(Compound) + 
#     as.factor(Type) + 
#     as.factor(Subplot), 
#     random = ~ 1 | Flower_index, data = gaussian_data_long)
# 
# summary(fixed_slope_lme)
# 
# random_slope_lme <- lme(Width ~ Day +
#     as.factor(Compound) + 
#     as.factor(Type) + 
#     as.factor(Subplot), 
#     random = ~ Day | Flower_index, data = gaussian_data_long)
# 
# summary(random_slope_lme)
```


```{r}
sum_gaussian_data <- gaussian_data_long %>% 
  group_by(Day, Compound) %>% 
  summarise(Mean_width = mean(Width))

sum_gaussian_data

gaussian_data_long_copy <- gaussian_data_long

gaussian_data_long_copy$Compound <-
  factor(
    gaussian_data_long_copy$Compound,
    labels = c(
      "Distilled Water",
      "Apathic Acid",
      "Beerse Brew",
      "Concentrate of Caducues",
      "Distilled of Discovery",
      "Essence of Epiphanea",
      "Four in December",
      "Granule of Geheref",
      "Kar-Hamel Mooh",
      "Lucifer’s Liquid",
      "Noospherol",
      "Oil of John’s Son",
      "Powder of Perlimpinpin",
      "Spirit of Scienza",
      "Zest of Zen"
    )
  )

sum_gaussian_data %>%
  ggplot(aes(Day, Mean_width, color = as.factor(Compound))) + geom_line()

gaussian_data_long_copy %>%
  ggplot(aes(Day, Width, color = Compound)) +
  geom_smooth(size = 0.75, method = "lm", se = F)
```     


```{r}
gaussian_data_long$Type_factor <- as.factor(gaussian_data_long$Type)
gaussian_data_long$Compound_factor <- as.factor(gaussian_data_long$Compound)
gaussian_data_long$Flower_index_factor <- as.factor(gaussian_data_long$Flower_index)
gaussian_data_long$Subplot_factor <- as.factor(gaussian_data_long$Subplot)
gaussian_data_long$Garden_factor <- as.factor(gaussian_data_long$Garden)
```


```{r}
fixed_slope_lmer <- lmer(
  Width ~ Day +
    Day:Compound_factor + 
    Garden_factor +
    Type_factor + 
    (1 | Subplot_factor) +
    (1 | Flower_index_factor),
  data = gaussian_data_long
)

anova(fixed_slope_lmer)

print(summary(fixed_slope_lmer), correlation = FALSE)
```


```{r}
random_slope_lmer <- lmer(
  Width ~ Day +
    Compound_factor:Day + 
    Type_factor + 
    Garden_factor +
    (1 | Subplot_factor) +
    (Day | Flower_index),
  data = gaussian_data_long,
  control=lmerControl(optimizer="optimx",
                       optCtrl=list(method="nlminb")) 
)

anova(random_slope_lmer)

print(summary(random_slope_lmer), correlation = FALSE)
```


```{r}
confint(random_slope_lmer, method = "Wald")
```


```{r}
emm = emmeans(random_slope_lmer, ~ Compound_factor | Day)
contrast(emm, method = "dunnett", adjust = "bonferroni")
```

















